-- Flyway Migration V1: Create canonical genomic schema
-- Educational/research purposes only - not for medical diagnosis or treatment
--
-- This migration creates the canonical storage schema for genomic variant data
-- with proper provenance tracking and indexing for efficient queries.
--
-- Compatible with both PostgreSQL and H2 databases.

-- ============================================================================
-- Table: samples
-- Stores metadata about imported genomic files with full provenance tracking
-- ============================================================================
CREATE TABLE samples (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    file_hash VARCHAR(64) NOT NULL UNIQUE,
    import_format VARCHAR(50) NOT NULL,
    genome_build VARCHAR(50),
    parser_version VARCHAR(20) NOT NULL,
    imported_at TIMESTAMP NOT NULL,
    original_filename VARCHAR(500),
    file_size_bytes BIGINT,
    variant_count INTEGER DEFAULT 0,
    rejected_line_count INTEGER DEFAULT 0,
    import_status VARCHAR(20) DEFAULT 'SUCCESS',
    metadata TEXT,
    CONSTRAINT chk_import_status CHECK (import_status IN ('SUCCESS', 'PARTIAL', 'FAILED'))
);

-- Indexes for samples table
CREATE INDEX idx_samples_user_id ON samples(user_id);
CREATE INDEX idx_samples_file_hash ON samples(file_hash);
CREATE INDEX idx_samples_imported_at ON samples(imported_at);
CREATE INDEX idx_samples_import_format ON samples(import_format);
CREATE INDEX idx_samples_genome_build ON samples(genome_build);
CREATE INDEX idx_samples_import_status ON samples(import_status);

-- ============================================================================
-- Table: variant_calls
-- Stores individual genomic variant calls linked to their parent sample
-- ============================================================================
CREATE TABLE variant_calls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sample_id BIGINT NOT NULL,
    chrom VARCHAR(10) NOT NULL,
    pos BIGINT NOT NULL,
    rsid VARCHAR(50),
    ref VARCHAR(1000) NOT NULL,
    alt VARCHAR(1000) NOT NULL,
    genotype VARCHAR(50),
    qual DOUBLE PRECISION,
    filter VARCHAR(255),
    line_number INTEGER,
    source VARCHAR(50),
    annotations TEXT,
    CONSTRAINT fk_variant_call_sample FOREIGN KEY (sample_id)
        REFERENCES samples(id) ON DELETE CASCADE
);

-- Indexes for variant_calls table
CREATE INDEX idx_variant_calls_sample_id ON variant_calls(sample_id);
CREATE INDEX idx_variant_calls_chrom_pos ON variant_calls(chrom, pos);
CREATE INDEX idx_variant_calls_rsid ON variant_calls(rsid);
CREATE INDEX idx_variant_calls_chrom ON variant_calls(chrom);
CREATE INDEX idx_variant_calls_genotype ON variant_calls(genotype);
CREATE INDEX idx_variant_calls_filter ON variant_calls(filter);

-- ============================================================================
-- Comments for documentation
-- ============================================================================
COMMENT ON TABLE samples IS 'Genomic sample imports with full provenance tracking. Educational/research purposes only.';
COMMENT ON COLUMN samples.file_hash IS 'SHA-256 hash of original file for integrity verification';
COMMENT ON COLUMN samples.import_format IS 'Format of imported file (vcf, vcf.gz, generic_tsv, etc.)';
COMMENT ON COLUMN samples.genome_build IS 'Genome assembly version (GRCh37, GRCh38, hg19, hg38, etc.)';
COMMENT ON COLUMN samples.parser_version IS 'Version of parser used for reproducibility';
COMMENT ON COLUMN samples.variant_count IS 'Number of variants successfully imported';
COMMENT ON COLUMN samples.rejected_line_count IS 'Number of lines rejected during import';

COMMENT ON TABLE variant_calls IS 'Individual genomic variant calls. Educational/research purposes only.';
COMMENT ON COLUMN variant_calls.chrom IS 'Chromosome identifier (1-22, X, Y, MT)';
COMMENT ON COLUMN variant_calls.pos IS 'Genomic position (1-based coordinate)';
COMMENT ON COLUMN variant_calls.rsid IS 'Variant identifier (e.g., rs1234567)';
COMMENT ON COLUMN variant_calls.ref IS 'Reference allele';
COMMENT ON COLUMN variant_calls.alt IS 'Alternate allele';
COMMENT ON COLUMN variant_calls.genotype IS 'Genotype call (0/0, 0/1, 1/1, AA, AG, etc.)';
COMMENT ON COLUMN variant_calls.qual IS 'Quality score for variant call';
COMMENT ON COLUMN variant_calls.filter IS 'Filter status (PASS, LowQual, etc.)';
