package com.dna.integrator.anatomy.rules;

import com.dna.integrator.anatomy.model.Overlay;
import com.dna.integrator.model.VariantCallEntity;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.extern.slf4j.Slf4j;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Service;

import jakarta.annotation.PostConstruct;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Pattern;

/**
 * Rule engine that applies mapping rules from configuration to generate overlays.
 *
 * Educational/research purposes only - not for medical diagnosis or treatment.
 *
 * This engine is deterministic - same inputs always produce same outputs.
 */
@Service
@Slf4j
public class RuleEngine {

    private final ObjectMapper objectMapper;
    private MappingRuleConfig ruleConfig;

    public RuleEngine(ObjectMapper objectMapper) {
        this.objectMapper = objectMapper;
    }

    /**
     * Load mapping rules from configuration file on startup
     */
    @PostConstruct
    public void loadRules() {
        try {
            ClassPathResource resource = new ClassPathResource("mapping/rules_v1.json");
            ruleConfig = objectMapper.readValue(resource.getInputStream(), MappingRuleConfig.class);
            log.info("Loaded mapping rules version: {}", ruleConfig.getVersion());
            log.info("Rules loaded: {}", ruleConfig.getMappingRules().size());
        } catch (IOException e) {
            log.error("Failed to load mapping rules", e);
            throw new RuntimeException("Failed to load mapping rules configuration", e);
        }
    }

    /**
     * Get the loaded rule configuration
     */
    public MappingRuleConfig getRuleConfig() {
        return ruleConfig;
    }

    /**
     * Apply all matching rules to a variant and generate overlays
     *
     * @param variant The variant to evaluate
     * @return List of overlays generated by matching rules
     */
    public List<Overlay> applyRules(VariantCallEntity variant) {
        List<Overlay> overlays = new ArrayList<>();

        if (ruleConfig == null || ruleConfig.getMappingRules() == null) {
            log.warn("No mapping rules loaded");
            return overlays;
        }

        for (MappingRuleConfig.MappingRule rule : ruleConfig.getMappingRules()) {
            if (matchesRule(variant, rule)) {
                Overlay overlay = createOverlay(variant, rule);
                overlays.add(overlay);
                log.debug("Rule {} matched for variant at {}:{} - generated overlay for {}",
                         rule.getRuleId(), variant.getChrom(), variant.getPos(),
                         rule.getOutcome().getTargetNodeId());
            }
        }

        return overlays;
    }

    /**
     * Check if a variant matches a rule's conditions
     */
    private boolean matchesRule(VariantCallEntity variant, MappingRuleConfig.MappingRule rule) {
        MappingRuleConfig.RuleConditions conditions = rule.getConditions();

        // Check chromosome match
        if (conditions.getChrom() != null) {
            String normalizedChrom = normalizeChromosome(variant.getChrom());
            String conditionChrom = normalizeChromosome(conditions.getChrom());
            if (!normalizedChrom.equals(conditionChrom)) {
                return false;
            }
        }

        // Check rsID match
        if (conditions.getRsid() != null) {
            if (variant.getRsid() == null || !variant.getRsid().equals(conditions.getRsid())) {
                return false;
            }
        }

        // Check position range
        if (conditions.getPositionRange() != null) {
            Long pos = variant.getPos();
            MappingRuleConfig.PositionRange range = conditions.getPositionRange();
            if (pos < range.getMin() || pos > range.getMax()) {
                return false;
            }
        }

        // Check genotype pattern
        if (conditions.getGenotypePattern() != null) {
            if (variant.getGenotype() == null) {
                return false;
            }
            Pattern pattern = Pattern.compile(conditions.getGenotypePattern());
            if (!pattern.matcher(variant.getGenotype()).matches()) {
                return false;
            }
        }

        // Check quality minimum
        if (conditions.getQualityMin() != null) {
            if (variant.getQual() == null || variant.getQual() < conditions.getQualityMin()) {
                return false;
            }
        }

        return true;
    }

    /**
     * Create an overlay from a matched rule
     */
    private Overlay createOverlay(VariantCallEntity variant, MappingRuleConfig.MappingRule rule) {
        MappingRuleConfig.RuleOutcome outcome = rule.getOutcome();

        return Overlay.builder()
                .targetNodeId(outcome.getTargetNodeId())
                .intensity(outcome.getIntensity())
                .label(outcome.getLabel())
                .evidence(Overlay.EvidenceLevel.valueOf(outcome.getEvidence()))
                .sources(new ArrayList<>(outcome.getSources()))
                .build();
    }

    /**
     * Normalize chromosome naming (handle chr1 vs 1, chrX vs X, etc.)
     */
    private String normalizeChromosome(String chrom) {
        if (chrom == null) return "";
        String normalized = chrom.toUpperCase().trim();
        if (normalized.startsWith("CHR")) {
            normalized = normalized.substring(3);
        }
        return normalized;
    }

    /**
     * Get rules version
     */
    public String getRulesVersion() {
        return ruleConfig != null ? ruleConfig.getVersion() : "unknown";
    }
}
